defaults:
  - model: dynadust3r
  - optim: adam
  - sched: cosine
  - criterion: conf  # or regr3d, regr3d_shiftinv, etc.
  - dataset/pointodyssey@dataset.pointodyssey
  - _self_

train:
  epochs: 50
  grad_clip: 0
  val_interval: 20

valid:
  interval: 5
  save: 
    save_best: True
    best_metric: loss
    lower_is_better: True
    output_dir: weights/

data:
  loader: pointodyssey
  len: 2 # total triplets
  size: 512 # image size | also change in model/dynadust3r.yaml
  crop: True
  batch_size: 2
  num_workers: 12

logging:
  use_wandb: False
  wandb_interval: 1