name: stereo4d
path: /scratch/projects/fouheylab/km6748/stereo4d-data/
wds_dir: ???
cache: /scratch/projects/fouheylab/km6748/stereo4d-data/.cache
lefteye_dir: /scratch/projects/fouheylab/km6748/stereo4d-data/lefteye-perspective
sequences_csv: /scratch/km6748/vision-experiments/utils/data/stereo4d_all_sequences.csv
train_split: train # train, test
valid_split: test # train, test
# path: /scratch/projects/fouheylab/km6748/stereo4d-data/
# train_split: sample
# valid_split: sample
max_frame_window: 60
pm_source: 3d_tracks # dm / 3d_tracks

# dataset specific
hfov: 60